# Site settings
show_downloads: false
title: "Forklift Documentation"
permalink: pretty
repository: konveyor/forklift-documentation
baseurl: /
tags: "migration, VMware, OpenShift Virtualization, KubeVirt, migrating, virtual machines, OpenShift"

logo: "/assets/img/forklift-logo-darkbg.svg"
type: website
future: false

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

plugins: [jekyll-paginate, jekyll-asciidoc, jekyll-redirect-from, jekyll-feed, jekyll-sitemap, premonition, jekyll/tagging,  jekyll-seo-tag]

# empty array for asciidoc
asciidoc: {}
# upstream doc attributes
asciidoctor:
  attributes:
  - title=Installing and using Forklift
  - context=forklift
  - description=Migrating virtual machines to KubeVirt
  - abstract=Forklift enables you to migrate virtual machines to {virt} running on {ocp}.
  - author=Red Hat Modernization and Migration Solutions documentation team
  - showtitle=@
  - build=upstream
  - imagesdir=../modules/images
  - must-gather=quay.io/konveyor/forklift-must-gather:latest
  - namespace=konveyor-forklift
  - ocp=OKD
  - ocp-version=4.7
  - ocp-short=OKD
  - operator=forklift-operator
  - operator-name=Forklift Operator
  - project-short=Forklift
  - project-full=Forklift
  - project-first=Forklift
  - project-version=2.0
  - project-z-version=2.0.0
  - the-lc=
  - the=
  - virt=KubeVirt
  safe: unsafe

exclude:
  - README.md
  - .history

tag_page_layout: tag
tag_page_dir: /tag/

kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
