# Site settings
show_downloads: false
title: "Forklift Documentation"
permalink: pretty
repository: konveyor/forklift-documentation
baseurl: /forklift-documentation/
logo: "/assets/img/forklift-logo-darkbg.svg"
type: website
future: false

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

plugins: [jekyll-paginate, jekyll-asciidoc, jekyll-redirect-from, jekyll-feed, jekyll-sitemap, premonition, jekyll/tagging,  jekyll-seo-tag]

# empty array for asciidoc
asciidoc: {}
# upstream doc attributes
asciidoctor:
  attributes:
  - context=forklift
  - description=Migrating virtual machines to KubeVirt
  - keywords=migration, VMware, OpenShift Virtualization, KubeVirt
  - author=Red Hat Modernization and Migration Solutions documentation team
  - showtitle=@
  - build=upstream
  - imagesdir=../modules/images
  - project-short=Forklift
  - project-full=Forklift
  - project-first=Forklift
  - the-lc=
  - The=
  - project-version=2.0-beta
  - virt=KubeVirt
  - ocp=OpenShift Kubernetes Engine
  - ocp-version=4.6
  - ocp-short=OKE
  - operator=Konveyor Forklift Operator
  safe: unsafe

exclude:
  - README.md
  - .history

tag_page_layout: tag
tag_page_dir: /tag/

kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
