# Site settings
show_downloads: false
title: "Forklift documentation"
description: "Forklift is an upstream project for migrating VMware virtual machines to OpenShift Virtualization. The downstream project is Migration Toolkit for Virtualization."
permalink: pretty
repository: konveyor/forklift-documentation
baseurl: /forklift-documentation/
logo: "/assets/img/forklift-logo-lightbg.svg"
type: website
future: false

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

plugins: [jekyll-paginate, jekyll-asciidoc, jekyll-redirect-from, jekyll-feed, jekyll-sitemap, premonition, jekyll/tagging,  jekyll-seo-tag]

# empty array for asciidoc
asciidoc: {}
# upstream doc attributes
asciidoctor:
  attributes:
  - showtitle=@
  - build=upstream
  - project-short=Forklift
  - project-full=Forklift
  - project-first=Forklift
  - project-version=2.0
  - virt=KubeVirt
  - ocp=OpenShift{nbsp}Kubernetes{nbsp}Engine
  - ocp-version=4.6
  - ocp-short=OKE
  - context=forklift
  safe: unsafe

exclude:
  - README.md
  - .history

tag_page_layout: tag
tag_page_dir: /tag/

kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
