include::modules/common-attributes.adoc[]
[id="{rn-title}_{context}"]
= {rn-title}

:toc:
:toclevels: 3
:compat-mode:
:context: release-notes

ifeval::["{build}" == "downstream"]
include::modules/making-open-source-more-inclusive.adoc[]
endif::[]

== {project-full} {project-version} release notes

{the} {project-first} enables you to migrate virtual machines from VMware vSphere or {rhv-full} to {virt} {ocp-version}. With {virt}, you can manage virtual machine workloads alongside container workloads.

This document describes new features and enhancements, known issues, and resolved issues for {the-lc} {project-full} {project-version}.

[id="new-features-and-enhancements_{context}"]
=== New features and enhancements

This release adds the following features and improvements.

[id="cold-migration-from-rhv_{context}"]
==== Cold migration from {rhv-full}

This release supports cold migration of virtual machines from {rhv-full}.

[id="migration-hooks_{context}"]
==== Migration hooks

This release supports migration hooks, which run Ansible playbooks before or after migration.

[id="filtered-must-gather-data-collection_{context}"]
==== Filtered must-gather data collection

This release supports options for the `must-gather` tool that enable you to filter the data by namespace, migration plan, or virtual machines.

[id="technical-changes_{context}"]
=== Technical changes

In the current release, the VMware Virtual Disk Development Kit (VDDK) SDK image is added to the `HyperConverged` custom resource. Previously, it was added to the `v2v-vmware` config map.
