# Site settings
show_downloads: false
title: 'Forklift'
description: "Forkstream is an upstream project for migrating VMware virtual machines to OpenShift Virtualization. The downstream project is Migration Toolkit for Virtualization."
permalink: pretty
repository: konveyor/forklift-documentation
baseurl: /forklift-documentation/
logo: "/assets/img/forklift-logo-lightbg.svg"
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

plugins: [jekyll-paginate, jekyll-asciidoc, jekyll-redirect-from, jekyll-feed, jekyll-sitemap, premonition, jekyll/tagging,  jekyll-seo-tag]

# Site settings
future: false

# Build settings
markdown: kramdown
type: website

exclude:
  - GUIDELINES.md
  - README.md
  - TODO.md
  - .history

tag_page_layout: tag
tag_page_dir: /tag/

kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
